services:
  disjfa_picture.picture_menu_listener:
    class: Disjfa\PictureBundle\GlynnAdminMenu\PictureMenuListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure' }
