services:
  disjfa_media.media_menu_listener:
    class: Disjfa\MediaBundle\GlynnAdminMenu\MediaMenuListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure' }
