services:
  disjfa_builder.builder_menu_listener:
    class: Disjfa\BuilderBundle\GlynnAdminMenu\BuilderMenuListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure' }
