services:
  user.user_menu_listener:
    class: UserBundle\GlynnAdminMenu\UserMenuListener
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.token_storage'
    tags:
      - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure', priority: -50 }
